<?php

use Illuminate\Database\Seeder;

class AsientosSeederTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $asientos = [
        	 ['fila' => '1',
        	 'columna' => '1',],
             ['fila' => '1',
             'columna' => '2',],
             ['fila' => '1',
             'columna' => '3',],
             ['fila' => '1',
             'columna' => '4',],
             ['fila' => '1',
             'columna' => '5',],
             ['fila' => '1',
             'columna' => '6',],
             ['fila' => '1',
             'columna' => '7',],
             ['fila' => '1',
             'columna' => '8',],
             ['fila' => '1',
             'columna' => '9',],
             ['fila' => '1',
             'columna' => '10',],
             ['fila' => '2',
        	 'columna' => '1',],
             ['fila' => '2',
             'columna' => '2',],
             ['fila' => '2',
             'columna' => '3',],
             ['fila' => '2',
             'columna' => '4',],
             ['fila' => '2',
             'columna' => '5',],
             ['fila' => '2',
             'columna' => '6',],
             ['fila' => '2',
             'columna' => '7',],
             ['fila' => '2',
             'columna' => '8',],
             ['fila' => '2',
             'columna' => '9',],
             ['fila' => '2',
             'columna' => '10',],
             ['fila' => '3',
        	 'columna' => '1',],
             ['fila' => '3',
             'columna' => '2',],
             ['fila' => '3',
             'columna' => '3',],
             ['fila' => '3',
             'columna' => '4',],
             ['fila' => '3',
             'columna' => '5',],
             ['fila' => '3',
             'columna' => '6',],
             ['fila' => '3',
             'columna' => '7',],
             ['fila' => '3',
             'columna' => '8',],
             ['fila' => '3',
             'columna' => '9',],
             ['fila' => '3',
             'columna' => '10',],
             ['fila' => '4',
        	 'columna' => '1',],
             ['fila' => '4',
             'columna' => '2',],
             ['fila' => '4',
             'columna' => '3',],
             ['fila' => '4',
             'columna' => '4',],
             ['fila' => '4',
             'columna' => '5',],
             ['fila' => '4',
             'columna' => '6',],
             ['fila' => '4',
             'columna' => '7',],
             ['fila' => '4',
             'columna' => '8',],
             ['fila' => '4',
             'columna' => '9',],
             ['fila' => '4',
             'columna' => '10',],
             ['fila' => '5',
        	 'columna' => '1',],
             ['fila' => '5',
             'columna' => '2',],
             ['fila' => '5',
             'columna' => '3',],
             ['fila' => '5',
             'columna' => '4',],
             ['fila' => '5',
             'columna' => '5',],
             ['fila' => '5',
             'columna' => '6',],
             ['fila' => '5',
             'columna' => '7',],
             ['fila' => '5',
             'columna' => '8',],
             ['fila' => '5',
             'columna' => '9',],
             ['fila' => '5',
             'columna' => '10',],

         ];
        DB::table('asientos')->insert($asientos);
    }
}
